#!/usr/bin/python -OO
#
#    Straight Python version of prime number tests in misc languages
#    Copyright (C) 2002 Hans Ulrich Niedermann <primes@n-dimensional.de>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

def sqrt(x):
    if x <= 0:
        return x
    i = x/2
    while 1:
        l = i
        i = (i + x/i)/2
        if abs(l-i) <= 1:
            return (i+x/i)/2

p = [0] * (1<<16)
p[0] = 2
p[1] = 3
for i in range(2,1<<16):
    p[i] = p[i-1] + 2;
    k = 1
    s = sqrt(p[i])
    while (k<i) and (p[k] <= s):
        if (p[i] % p[k]) == 0:
            p[i] += 2
            k = 1
            s = sqrt(p[i])
        else:
            k += 1

for i in range(0, 1<<16):
    print "%u %u" % (i, p[i])


# Local Variables:
# mode:python
# End:
